// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	ActOnThreadOperation           OperationName = "ActOnThread"
	AddPeerOperation               OperationName = "AddPeer"
	ApproveRequestOperation        OperationName = "ApproveRequest"
	CreateAgentTokenOperation      OperationName = "CreateAgentToken"
	CreateWebhookOperation         OperationName = "CreateWebhook"
	DeleteAgentTokenOperation      OperationName = "DeleteAgentToken"
	DeleteWebhookOperation         OperationName = "DeleteWebhook"
	DeliverEventOperation          OperationName = "DeliverEvent"
	DenyRequestOperation           OperationName = "DenyRequest"
	GetHealthOperation             OperationName = "GetHealth"
	GetMeOperation                 OperationName = "GetMe"
	GetPeerOperation               OperationName = "GetPeer"
	GetThreadOperation             OperationName = "GetThread"
	GetWebhookOperation            OperationName = "GetWebhook"
	ListAgentTokensOperation       OperationName = "ListAgentTokens"
	ListPeersOperation             OperationName = "ListPeers"
	ListRequestsOperation          OperationName = "ListRequests"
	ListThreadsOperation           OperationName = "ListThreads"
	ListWebhookDeliveriesOperation OperationName = "ListWebhookDeliveries"
	ListWebhooksOperation          OperationName = "ListWebhooks"
	NotifyPeeringAcceptedOperation OperationName = "NotifyPeeringAccepted"
	OpenThreadOperation            OperationName = "OpenThread"
	RemovePeerOperation            OperationName = "RemovePeer"
	RequestPeeringOperation        OperationName = "RequestPeering"
	RetryWebhookDeliveryOperation  OperationName = "RetryWebhookDelivery"
	UpdateWebhookOperation         OperationName = "UpdateWebhook"
)
