// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	ActOnThreadOperation           OperationName = "ActOnThread"
	AddPeerOperation               OperationName = "AddPeer"
	ApproveRequestOperation        OperationName = "ApproveRequest"
	DeliverEventOperation          OperationName = "DeliverEvent"
	DenyRequestOperation           OperationName = "DenyRequest"
	GetHealthOperation             OperationName = "GetHealth"
	GetMeOperation                 OperationName = "GetMe"
	GetPeerOperation               OperationName = "GetPeer"
	GetThreadOperation             OperationName = "GetThread"
	ListPeersOperation             OperationName = "ListPeers"
	ListRequestsOperation          OperationName = "ListRequests"
	ListThreadsOperation           OperationName = "ListThreads"
	NotifyPeeringAcceptedOperation OperationName = "NotifyPeeringAccepted"
	OpenThreadOperation            OperationName = "OpenThread"
	RemovePeerOperation            OperationName = "RemovePeer"
	RequestPeeringOperation        OperationName = "RequestPeering"
)
