// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActOnThread implements actOnThread operation.
	//
	// Fails with 409 when the owner may not take the action now; the thread's `actions` lists the ones
	// they may. Either participant can close an open, acked, needs-input or resolved thread, or reopen a
	// resolved or closed thread with a reason. A missing or whitespace-only reopen reason fails with 400.
	// Each side has room for 1000 events and 4 MiB of bodies in a thread; past that, only close, decline
	// or withdraw without a body remain. An agent token limited to peers reaches only threads with those
	// peers, as getThread.
	//
	// POST /api/v1/threads/{ref}/events
	ActOnThread(ctx context.Context, req *ThreadAction, params ActOnThreadParams) (*ThreadSummary, error)
	// AddPeer implements addPeer operation.
	//
	// Makes a secret, sends it with a peering request to the daemon at `url`, and saves the peer as
	// `requested`. Events to them queue until their owner approves; then they deliver. Fails with 502 when
	// their daemon cannot be reached, and saves nothing. Fails with 409 when the name or URL already
	// belongs to a peer; each daemon has one name here. Trailing slashes on daemon URLs are removed. The
	// URL must reach the daemon directly; redirects are refused.
	//
	// POST /api/v1/peers
	AddPeer(ctx context.Context, req *PeerInput) (*Peer, error)
	// ApproveRequest implements approveRequest operation.
	//
	// First calls the requester's daemon, at the URL it gave, with the secret it offered: only if that
	// daemon confirms does the requester become a peer, under the name given or the one they asked for. So
	// a request cannot claim someone else's URL. Fails with 502 when their daemon does not confirm; the
	// request stays. No events are accepted under the offered secret before confirmation succeeds. If
	// confirmation is interrupted, the request and any previous peer are left unchanged. The URL must
	// reach the daemon directly; redirects are refused.
	//
	// POST /api/v1/peering-requests/{id}/approve
	ApproveRequest(ctx context.Context, req *Approval, params ApproveRequestParams) (*Peer, error)
	// CreateAgentToken implements createAgentToken operation.
	//
	// The token is returned once and only its hash is stored. It may list, read and act on threads, follow
	// the stream and read the owner's name; every other operation refuses it with 403. Fails with 409 when
	// the name is taken, and with 400 when `expiresAt` is not in the future.
	//
	// POST /api/v1/agent-tokens
	CreateAgentToken(ctx context.Context, req *AgentTokenInput) (*NewAgentToken, error)
	// CreateWebhook implements createWebhook operation.
	//
	// Only future matching events are queued; secrets are never returned.
	//
	// POST /api/v1/webhooks
	CreateWebhook(ctx context.Context, req *WebhookCreate) (*Webhook, error)
	// DeleteAgentToken implements deleteAgentToken operation.
	//
	// The token stops working at once. A stream it opened sends nothing more and closes at its next event
	// or keepalive.
	//
	// DELETE /api/v1/agent-tokens/{name}
	DeleteAgentToken(ctx context.Context, params DeleteAgentTokenParams) error
	// DeleteWebhook implements deleteWebhook operation.
	//
	// Deletes configuration and delivery history, including pending deliveries. An in-flight request may
	// finish.
	//
	// DELETE /api/v1/webhooks/{name}
	DeleteWebhook(ctx context.Context, params DeleteWebhookParams) error
	// DeliverEvent implements deliverEvent operation.
	//
	// The peer's secret says who sent it. Delivering the same event again is harmless and answers
	// `duplicate`. Fails with 422 when its thread is unknown or not shared with this peer, or its clock is
	// not after the peer's earlier events in the thread, or the peer has used its room in the thread (1000
	// events, 4 MiB of bodies; then only close, decline or withdraw without a body); with 503, to retry
	// later, when it is dated more than ten minutes ahead.
	//
	// POST /api/v1/federation/events
	DeliverEvent(ctx context.Context, req *Event) (*Receipt, error)
	// DenyRequest implements denyRequest operation.
	//
	// Drops the request; nothing is sent to the requester.
	//
	// DELETE /api/v1/peering-requests/{id}
	DenyRequest(ctx context.Context, params DenyRequestParams) error
	// GetHealth implements getHealth operation.
	//
	// Answers while the daemon is serving; for load balancers and uptime checks.
	//
	// GET /api/v1/health
	GetHealth(ctx context.Context) (*Health, error)
	// GetMe implements getMe operation.
	//
	// The name this daemon offers peers, and the URL it gives them to call back on.
	//
	// GET /api/v1/me
	GetMe(ctx context.Context) (*Me, error)
	// GetPeer implements getPeer operation.
	//
	// One peer, with the short code of the secret you share.
	//
	// GET /api/v1/peers/{name}
	GetPeer(ctx context.Context, params GetPeerParams) (*Peer, error)
	// GetThread implements getThread operation.
	//
	// The thread's summary and every event, in the order both daemons replay them. The ref is a thread ID
	// or a unique prefix of one; for an agent token limited to peers, only threads with those peers count,
	// and any other answers 404 as if it did not exist.
	//
	// GET /api/v1/threads/{ref}
	GetThread(ctx context.Context, params GetThreadParams) (*Thread, error)
	// GetWebhook implements getWebhook operation.
	//
	// Read a webhook.
	//
	// GET /api/v1/webhooks/{name}
	GetWebhook(ctx context.Context, params GetWebhookParams) (*Webhook, error)
	// ListAgentTokens implements listAgentTokens operation.
	//
	// Every agent token, by name, without the tokens themselves.
	//
	// GET /api/v1/agent-tokens
	ListAgentTokens(ctx context.Context) (*AgentTokenList, error)
	// ListPeers implements listPeers operation.
	//
	// Every peer, requested or active.
	//
	// GET /api/v1/peers
	ListPeers(ctx context.Context) (*PeerList, error)
	// ListRequests implements listRequests operation.
	//
	// Requests not yet approved or denied, from the last week. Compare each code with the requester before
	// approving.
	//
	// GET /api/v1/peering-requests
	ListRequests(ctx context.Context) (*RequestList, error)
	// ListThreads implements listThreads operation.
	//
	// Newest activity first. An agent token limited to peers lists only threads with those peers.
	//
	// GET /api/v1/threads
	ListThreads(ctx context.Context, params ListThreadsParams) (*ThreadList, error)
	// ListWebhookDeliveries implements listWebhookDeliveries operation.
	//
	// Newest-first delivery history with cursor pagination. Pending deliveries retry for up to seven days;
	// terminal history is kept for seven days. Delivery IDs stay fixed across retries. Delivery order is
	// not guaranteed.
	//
	// GET /api/v1/webhooks/{name}/deliveries
	ListWebhookDeliveries(ctx context.Context, params ListWebhookDeliveriesParams) (*WebhookDeliveryList, error)
	// ListWebhooks implements listWebhooks operation.
	//
	// List webhooks.
	//
	// GET /api/v1/webhooks
	ListWebhooks(ctx context.Context) (*WebhookList, error)
	// NotifyPeeringAccepted implements notifyPeeringAccepted operation.
	//
	// The approving daemon calls this with the shared secret, so the requester starts delivering at once
	// instead of at its next retry.
	//
	// POST /api/v1/federation/accepted
	NotifyPeeringAccepted(ctx context.Context) error
	// OpenThread implements openThread operation.
	//
	// The thread is stored and queued for delivery to the peer.
	//
	// POST /api/v1/threads
	OpenThread(ctx context.Context, req *NewThread) (*ThreadSummary, error)
	// RemovePeer implements removePeer operation.
	//
	// Their secret stops working and undelivered events to them fail. Threads are kept, so their name can
	// later go only to a peer at the same URL.
	//
	// DELETE /api/v1/peers/{name}
	RemovePeer(ctx context.Context, params RemovePeerParams) error
	// RequestPeering implements requestPeering operation.
	//
	// Another daemon asks this one's owner to accept it as a peer, offering the secret both will use.
	// Nothing is accepted from it until the owner approves. Requests expire after a week; at most 20 wait,
	// and a new one drops the oldest. Past 10 requests a minute it answers 503.
	//
	// POST /api/v1/peering-requests
	RequestPeering(ctx context.Context, req *PeeringRequest) (*RequestReceipt, error)
	// RetryWebhookDelivery implements retryWebhookDelivery operation.
	//
	// Resets a failed delivery for another seven days of retries, retaining its ID and payload, and clears
	// the endpoint's failure backoff. Requires an enabled webhook. Refuses pending or delivered items with
	// 409.
	//
	// POST /api/v1/webhooks/{name}/deliveries/{id}/retry
	RetryWebhookDelivery(ctx context.Context, params RetryWebhookDeliveryParams) error
	// UpdateWebhook implements updateWebhook operation.
	//
	// Changes only supplied settings. The destination type is immutable. Omit url, headers or secret to
	// keep them; an empty secret disables signing and empty headers remove custom headers. Pending
	// deliveries use the current destination and credentials. Disabled webhooks queue no new events and
	// pause existing deliveries; an in-flight request may finish. Any update clears the endpoint's failure
	// backoff (pausedUntil).
	//
	// PATCH /api/v1/webhooks/{name}
	UpdateWebhook(ctx context.Context, req *WebhookUpdate, params UpdateWebhookParams) (*Webhook, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
