// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAgentToken handles agentToken security.
	// An agent token the owner created; limited to existing threads.
	HandleAgentToken(ctx context.Context, operationName OperationName, t AgentToken) (context.Context, error)
	// HandleOwnerToken handles ownerToken security.
	// The owner token, from `<dir>/owner.token`.
	HandleOwnerToken(ctx context.Context, operationName OperationName, t OwnerToken) (context.Context, error)
	// HandlePeerSecret handles peerSecret security.
	// The secret shared with one peer.
	HandlePeerSecret(ctx context.Context, operationName OperationName, t PeerSecret) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAgentToken is a private map storing roles per operation.
var operationRolesAgentToken = map[string][]string{
	ActOnThreadOperation: []string{},
	GetMeOperation:       []string{},
	GetThreadOperation:   []string{},
	ListThreadsOperation: []string{},
}

// GetRolesForAgentToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAgentToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAgentToken(operation string) []string {
	roles, ok := operationRolesAgentToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesOwnerToken is a private map storing roles per operation.
var operationRolesOwnerToken = map[string][]string{
	ActOnThreadOperation:           []string{},
	AddPeerOperation:               []string{},
	ApproveRequestOperation:        []string{},
	CreateAgentTokenOperation:      []string{},
	CreateWebhookOperation:         []string{},
	DeleteAgentTokenOperation:      []string{},
	DeleteWebhookOperation:         []string{},
	DenyRequestOperation:           []string{},
	GetMeOperation:                 []string{},
	GetPeerOperation:               []string{},
	GetThreadOperation:             []string{},
	GetWebhookOperation:            []string{},
	ListAgentTokensOperation:       []string{},
	ListPeersOperation:             []string{},
	ListRequestsOperation:          []string{},
	ListThreadsOperation:           []string{},
	ListWebhookDeliveriesOperation: []string{},
	ListWebhooksOperation:          []string{},
	OpenThreadOperation:            []string{},
	RemovePeerOperation:            []string{},
	RetryWebhookDeliveryOperation:  []string{},
	UpdateWebhookOperation:         []string{},
}

// GetRolesForOwnerToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForOwnerToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForOwnerToken(operation string) []string {
	roles, ok := operationRolesOwnerToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesPeerSecret is a private map storing roles per operation.
var operationRolesPeerSecret = map[string][]string{
	DeliverEventOperation:          []string{},
	NotifyPeeringAcceptedOperation: []string{},
}

// GetRolesForPeerSecret returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForPeerSecret(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForPeerSecret(operation string) []string {
	roles, ok := operationRolesPeerSecret[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAgentToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AgentToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesAgentToken[operationName]
	rctx, err := s.sec.HandleAgentToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityOwnerToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t OwnerToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesOwnerToken[operationName]
	rctx, err := s.sec.HandleOwnerToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityPeerSecret(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t PeerSecret
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesPeerSecret[operationName]
	rctx, err := s.sec.HandlePeerSecret(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AgentToken provides agentToken security value.
	// An agent token the owner created; limited to existing threads.
	AgentToken(ctx context.Context, operationName OperationName) (AgentToken, error)
	// OwnerToken provides ownerToken security value.
	// The owner token, from `<dir>/owner.token`.
	OwnerToken(ctx context.Context, operationName OperationName) (OwnerToken, error)
	// PeerSecret provides peerSecret security value.
	// The secret shared with one peer.
	PeerSecret(ctx context.Context, operationName OperationName) (PeerSecret, error)
}

func (s *Client) securityAgentToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AgentToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AgentToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityOwnerToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OwnerToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OwnerToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityPeerSecret(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.PeerSecret(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"PeerSecret\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
