// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"fmt"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// What an event does. The recipient acks, asks (`needs-input`), resolves and declines; the sender
// closes, reopens and withdraws; either comments.
// Ref: #/components/schemas/Action
type Action string

const (
	ActionOpen       Action = "open"
	ActionComment    Action = "comment"
	ActionAck        Action = "ack"
	ActionNeedsInput Action = "needs-input"
	ActionResolve    Action = "resolve"
	ActionClose      Action = "close"
	ActionReopen     Action = "reopen"
	ActionDecline    Action = "decline"
	ActionWithdraw   Action = "withdraw"
)

// AllValues returns all Action values.
func (Action) AllValues() []Action {
	return []Action{
		ActionOpen,
		ActionComment,
		ActionAck,
		ActionNeedsInput,
		ActionResolve,
		ActionClose,
		ActionReopen,
		ActionDecline,
		ActionWithdraw,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Action) MarshalText() ([]byte, error) {
	switch s {
	case ActionOpen:
		return []byte(s), nil
	case ActionComment:
		return []byte(s), nil
	case ActionAck:
		return []byte(s), nil
	case ActionNeedsInput:
		return []byte(s), nil
	case ActionResolve:
		return []byte(s), nil
	case ActionClose:
		return []byte(s), nil
	case ActionReopen:
		return []byte(s), nil
	case ActionDecline:
		return []byte(s), nil
	case ActionWithdraw:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Action) UnmarshalText(data []byte) error {
	switch Action(data) {
	case ActionOpen:
		*s = ActionOpen
		return nil
	case ActionComment:
		*s = ActionComment
		return nil
	case ActionAck:
		*s = ActionAck
		return nil
	case ActionNeedsInput:
		*s = ActionNeedsInput
		return nil
	case ActionResolve:
		*s = ActionResolve
		return nil
	case ActionClose:
		*s = ActionClose
		return nil
	case ActionReopen:
		*s = ActionReopen
		return nil
	case ActionDecline:
		*s = ActionDecline
		return nil
	case ActionWithdraw:
		*s = ActionWithdraw
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// How to approve a peering request.
// Ref: #/components/schemas/Approval
type Approval struct {
	Name OptName `json:"name"`
}

// GetName returns the value of Name.
func (s *Approval) GetName() OptName {
	return s.Name
}

// SetName sets the value of Name.
func (s *Approval) SetName(val OptName) {
	s.Name = val
}

type Body string

type Code string

type Count int32

type DaemonURL url.URL

// How the owner's event is getting to the peer; absent on the peer's events.
// Ref: #/components/schemas/Delivery
type Delivery struct {
	// `pending`: not yet delivered; retried with backoff for a week. `delivered`: the peer stored it.
	// `failed`: never to be delivered: the peer refused it, retries ran out, or the peer was removed.
	Status        DeliveryStatus `json:"status"`
	Attempts      Count          `json:"attempts"`
	LastError     OptString      `json:"lastError"`
	NextAttemptAt OptDateTime    `json:"nextAttemptAt"`
	DeliveredAt   OptDateTime    `json:"deliveredAt"`
}

// GetStatus returns the value of Status.
func (s *Delivery) GetStatus() DeliveryStatus {
	return s.Status
}

// GetAttempts returns the value of Attempts.
func (s *Delivery) GetAttempts() Count {
	return s.Attempts
}

// GetLastError returns the value of LastError.
func (s *Delivery) GetLastError() OptString {
	return s.LastError
}

// GetNextAttemptAt returns the value of NextAttemptAt.
func (s *Delivery) GetNextAttemptAt() OptDateTime {
	return s.NextAttemptAt
}

// GetDeliveredAt returns the value of DeliveredAt.
func (s *Delivery) GetDeliveredAt() OptDateTime {
	return s.DeliveredAt
}

// SetStatus sets the value of Status.
func (s *Delivery) SetStatus(val DeliveryStatus) {
	s.Status = val
}

// SetAttempts sets the value of Attempts.
func (s *Delivery) SetAttempts(val Count) {
	s.Attempts = val
}

// SetLastError sets the value of LastError.
func (s *Delivery) SetLastError(val OptString) {
	s.LastError = val
}

// SetNextAttemptAt sets the value of NextAttemptAt.
func (s *Delivery) SetNextAttemptAt(val OptDateTime) {
	s.NextAttemptAt = val
}

// SetDeliveredAt sets the value of DeliveredAt.
func (s *Delivery) SetDeliveredAt(val OptDateTime) {
	s.DeliveredAt = val
}

// `pending`: not yet delivered; retried with backoff for a week. `delivered`: the peer stored it.
// `failed`: never to be delivered: the peer refused it, retries ran out, or the peer was removed.
type DeliveryStatus string

const (
	DeliveryStatusPending   DeliveryStatus = "pending"
	DeliveryStatusDelivered DeliveryStatus = "delivered"
	DeliveryStatusFailed    DeliveryStatus = "failed"
)

// AllValues returns all DeliveryStatus values.
func (DeliveryStatus) AllValues() []DeliveryStatus {
	return []DeliveryStatus{
		DeliveryStatusPending,
		DeliveryStatusDelivered,
		DeliveryStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DeliveryStatus) MarshalText() ([]byte, error) {
	switch s {
	case DeliveryStatusPending:
		return []byte(s), nil
	case DeliveryStatusDelivered:
		return []byte(s), nil
	case DeliveryStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DeliveryStatus) UnmarshalText(data []byte) error {
	switch DeliveryStatus(data) {
	case DeliveryStatusPending:
		*s = DeliveryStatusPending
		return nil
	case DeliveryStatusDelivered:
		*s = DeliveryStatusDelivered
		return nil
	case DeliveryStatusFailed:
		*s = DeliveryStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// DenyRequestNoContent is response for DenyRequest operation.
type DenyRequestNoContent struct{}

// One step in a thread, as daemons exchange it. Who sent it is the peer whose secret delivered it; it
// is for the receiving daemon's owner.
// Ref: #/components/schemas/Event
type Event struct {
	ID     ID `json:"id"`
	Thread ID `json:"thread"`
	// When it was written, by its author's clock; for display only.
	At time.Time `json:"at"`
	// Orders the thread: 1 for the open, then one more than the highest clock its author had seen in the
	// thread.
	Clock  int64         `json:"clock"`
	Action Action        `json:"action"`
	Title  OptTitle      `json:"title"`
	Kind   OptThreadKind `json:"kind"`
	Labels Labels        `json:"labels"`
	Body   OptBody       `json:"body"`
}

// GetID returns the value of ID.
func (s *Event) GetID() ID {
	return s.ID
}

// GetThread returns the value of Thread.
func (s *Event) GetThread() ID {
	return s.Thread
}

// GetAt returns the value of At.
func (s *Event) GetAt() time.Time {
	return s.At
}

// GetClock returns the value of Clock.
func (s *Event) GetClock() int64 {
	return s.Clock
}

// GetAction returns the value of Action.
func (s *Event) GetAction() Action {
	return s.Action
}

// GetTitle returns the value of Title.
func (s *Event) GetTitle() OptTitle {
	return s.Title
}

// GetKind returns the value of Kind.
func (s *Event) GetKind() OptThreadKind {
	return s.Kind
}

// GetLabels returns the value of Labels.
func (s *Event) GetLabels() Labels {
	return s.Labels
}

// GetBody returns the value of Body.
func (s *Event) GetBody() OptBody {
	return s.Body
}

// SetID sets the value of ID.
func (s *Event) SetID(val ID) {
	s.ID = val
}

// SetThread sets the value of Thread.
func (s *Event) SetThread(val ID) {
	s.Thread = val
}

// SetAt sets the value of At.
func (s *Event) SetAt(val time.Time) {
	s.At = val
}

// SetClock sets the value of Clock.
func (s *Event) SetClock(val int64) {
	s.Clock = val
}

// SetAction sets the value of Action.
func (s *Event) SetAction(val Action) {
	s.Action = val
}

// SetTitle sets the value of Title.
func (s *Event) SetTitle(val OptTitle) {
	s.Title = val
}

// SetKind sets the value of Kind.
func (s *Event) SetKind(val OptThreadKind) {
	s.Kind = val
}

// SetLabels sets the value of Labels.
func (s *Event) SetLabels(val Labels) {
	s.Labels = val
}

// SetBody sets the value of Body.
func (s *Event) SetBody(val OptBody) {
	s.Body = val
}

// The daemon is up.
// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
	// The daemon's clock when it answered.
	At time.Time `json:"at"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetAt returns the value of At.
func (s *Health) GetAt() time.Time {
	return s.At
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetAt sets the value of At.
func (s *Health) SetAt(val time.Time) {
	s.At = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ID string

type Label string

type Labels []Label

type ListThreadsTurn string

const (
	ListThreadsTurnMine   ListThreadsTurn = "mine"
	ListThreadsTurnTheirs ListThreadsTurn = "theirs"
	ListThreadsTurnNone   ListThreadsTurn = "none"
)

// AllValues returns all ListThreadsTurn values.
func (ListThreadsTurn) AllValues() []ListThreadsTurn {
	return []ListThreadsTurn{
		ListThreadsTurnMine,
		ListThreadsTurnTheirs,
		ListThreadsTurnNone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListThreadsTurn) MarshalText() ([]byte, error) {
	switch s {
	case ListThreadsTurnMine:
		return []byte(s), nil
	case ListThreadsTurnTheirs:
		return []byte(s), nil
	case ListThreadsTurnNone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListThreadsTurn) UnmarshalText(data []byte) error {
	switch ListThreadsTurn(data) {
	case ListThreadsTurnMine:
		*s = ListThreadsTurnMine
		return nil
	case ListThreadsTurnTheirs:
		*s = ListThreadsTurnTheirs
		return nil
	case ListThreadsTurnNone:
		*s = ListThreadsTurnNone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The daemon's owner, as peers see them.
// Ref: #/components/schemas/Me
type Me struct {
	Name    Name         `json:"name"`
	URL     OptDaemonURL `json:"url"`
	Version string       `json:"version"`
}

// GetName returns the value of Name.
func (s *Me) GetName() Name {
	return s.Name
}

// GetURL returns the value of URL.
func (s *Me) GetURL() OptDaemonURL {
	return s.URL
}

// GetVersion returns the value of Version.
func (s *Me) GetVersion() string {
	return s.Version
}

// SetName sets the value of Name.
func (s *Me) SetName(val Name) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *Me) SetURL(val OptDaemonURL) {
	s.URL = val
}

// SetVersion sets the value of Version.
func (s *Me) SetVersion(val string) {
	s.Version = val
}

type Name string

// A thread to open with a peer.
// Ref: #/components/schemas/NewThread
type NewThread struct {
	To     Name          `json:"to"`
	Title  Title         `json:"title"`
	Kind   OptThreadKind `json:"kind"`
	Labels Labels        `json:"labels"`
	Body   OptBody       `json:"body"`
}

// GetTo returns the value of To.
func (s *NewThread) GetTo() Name {
	return s.To
}

// GetTitle returns the value of Title.
func (s *NewThread) GetTitle() Title {
	return s.Title
}

// GetKind returns the value of Kind.
func (s *NewThread) GetKind() OptThreadKind {
	return s.Kind
}

// GetLabels returns the value of Labels.
func (s *NewThread) GetLabels() Labels {
	return s.Labels
}

// GetBody returns the value of Body.
func (s *NewThread) GetBody() OptBody {
	return s.Body
}

// SetTo sets the value of To.
func (s *NewThread) SetTo(val Name) {
	s.To = val
}

// SetTitle sets the value of Title.
func (s *NewThread) SetTitle(val Title) {
	s.Title = val
}

// SetKind sets the value of Kind.
func (s *NewThread) SetKind(val OptThreadKind) {
	s.Kind = val
}

// SetLabels sets the value of Labels.
func (s *NewThread) SetLabels(val Labels) {
	s.Labels = val
}

// SetBody sets the value of Body.
func (s *NewThread) SetBody(val OptBody) {
	s.Body = val
}

type Note string

// NotifyPeeringAcceptedNoContent is response for NotifyPeeringAccepted operation.
type NotifyPeeringAcceptedNoContent struct{}

// NewOptBody returns new OptBody with value set to v.
func NewOptBody(v Body) OptBody {
	return OptBody{
		Value: v,
		Set:   true,
	}
}

// OptBody is optional Body.
type OptBody struct {
	Value Body
	Set   bool
}

// IsSet returns true if OptBody was set.
func (o OptBody) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBody) Reset() {
	var v Body
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBody) SetTo(v Body) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBody) Get() (v Body, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBody) Or(d Body) Body {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDaemonURL returns new OptDaemonURL with value set to v.
func NewOptDaemonURL(v DaemonURL) OptDaemonURL {
	return OptDaemonURL{
		Value: v,
		Set:   true,
	}
}

// OptDaemonURL is optional DaemonURL.
type OptDaemonURL struct {
	Value DaemonURL
	Set   bool
}

// IsSet returns true if OptDaemonURL was set.
func (o OptDaemonURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDaemonURL) Reset() {
	var v DaemonURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDaemonURL) SetTo(v DaemonURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDaemonURL) Get() (v DaemonURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDaemonURL) Or(d DaemonURL) DaemonURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDelivery returns new OptDelivery with value set to v.
func NewOptDelivery(v Delivery) OptDelivery {
	return OptDelivery{
		Value: v,
		Set:   true,
	}
}

// OptDelivery is optional Delivery.
type OptDelivery struct {
	Value Delivery
	Set   bool
}

// IsSet returns true if OptDelivery was set.
func (o OptDelivery) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDelivery) Reset() {
	var v Delivery
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDelivery) SetTo(v Delivery) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDelivery) Get() (v Delivery, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDelivery) Or(d Delivery) Delivery {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLabel returns new OptLabel with value set to v.
func NewOptLabel(v Label) OptLabel {
	return OptLabel{
		Value: v,
		Set:   true,
	}
}

// OptLabel is optional Label.
type OptLabel struct {
	Value Label
	Set   bool
}

// IsSet returns true if OptLabel was set.
func (o OptLabel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLabel) Reset() {
	var v Label
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLabel) SetTo(v Label) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLabel) Get() (v Label, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLabel) Or(d Label) Label {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListThreadsTurn returns new OptListThreadsTurn with value set to v.
func NewOptListThreadsTurn(v ListThreadsTurn) OptListThreadsTurn {
	return OptListThreadsTurn{
		Value: v,
		Set:   true,
	}
}

// OptListThreadsTurn is optional ListThreadsTurn.
type OptListThreadsTurn struct {
	Value ListThreadsTurn
	Set   bool
}

// IsSet returns true if OptListThreadsTurn was set.
func (o OptListThreadsTurn) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListThreadsTurn) Reset() {
	var v ListThreadsTurn
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListThreadsTurn) SetTo(v ListThreadsTurn) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListThreadsTurn) Get() (v ListThreadsTurn, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListThreadsTurn) Or(d ListThreadsTurn) ListThreadsTurn {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptName returns new OptName with value set to v.
func NewOptName(v Name) OptName {
	return OptName{
		Value: v,
		Set:   true,
	}
}

// OptName is optional Name.
type OptName struct {
	Value Name
	Set   bool
}

// IsSet returns true if OptName was set.
func (o OptName) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptName) Reset() {
	var v Name
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptName) SetTo(v Name) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptName) Get() (v Name, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptName) Or(d Name) Name {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNote returns new OptNote with value set to v.
func NewOptNote(v Note) OptNote {
	return OptNote{
		Value: v,
		Set:   true,
	}
}

// OptNote is optional Note.
type OptNote struct {
	Value Note
	Set   bool
}

// IsSet returns true if OptNote was set.
func (o OptNote) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNote) Reset() {
	var v Note
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNote) SetTo(v Note) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNote) Get() (v Note, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNote) Or(d Note) Note {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptThreadKind returns new OptThreadKind with value set to v.
func NewOptThreadKind(v ThreadKind) OptThreadKind {
	return OptThreadKind{
		Value: v,
		Set:   true,
	}
}

// OptThreadKind is optional ThreadKind.
type OptThreadKind struct {
	Value ThreadKind
	Set   bool
}

// IsSet returns true if OptThreadKind was set.
func (o OptThreadKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptThreadKind) Reset() {
	var v ThreadKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptThreadKind) SetTo(v ThreadKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptThreadKind) Get() (v ThreadKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptThreadKind) Or(d ThreadKind) ThreadKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptThreadState returns new OptThreadState with value set to v.
func NewOptThreadState(v ThreadState) OptThreadState {
	return OptThreadState{
		Value: v,
		Set:   true,
	}
}

// OptThreadState is optional ThreadState.
type OptThreadState struct {
	Value ThreadState
	Set   bool
}

// IsSet returns true if OptThreadState was set.
func (o OptThreadState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptThreadState) Reset() {
	var v ThreadState
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptThreadState) SetTo(v ThreadState) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptThreadState) Get() (v ThreadState, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptThreadState) Or(d ThreadState) ThreadState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTitle returns new OptTitle with value set to v.
func NewOptTitle(v Title) OptTitle {
	return OptTitle{
		Value: v,
		Set:   true,
	}
}

// OptTitle is optional Title.
type OptTitle struct {
	Value Title
	Set   bool
}

// IsSet returns true if OptTitle was set.
func (o OptTitle) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTitle) Reset() {
	var v Title
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTitle) SetTo(v Title) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTitle) Get() (v Title, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTitle) Or(d Title) Title {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type OwnerToken struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *OwnerToken) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *OwnerToken) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *OwnerToken) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *OwnerToken) SetRoles(val []string) {
	s.Roles = val
}

// A daemon this one exchanges threads with.
// Ref: #/components/schemas/Peer
type Peer struct {
	Name Name      `json:"name"`
	URL  DaemonURL `json:"url"`
	// `requested`: waiting for their owner to approve. `active`: both sides accept the secret.
	Status  PeerStatus `json:"status"`
	Code    Code       `json:"code"`
	AddedAt time.Time  `json:"addedAt"`
}

// GetName returns the value of Name.
func (s *Peer) GetName() Name {
	return s.Name
}

// GetURL returns the value of URL.
func (s *Peer) GetURL() DaemonURL {
	return s.URL
}

// GetStatus returns the value of Status.
func (s *Peer) GetStatus() PeerStatus {
	return s.Status
}

// GetCode returns the value of Code.
func (s *Peer) GetCode() Code {
	return s.Code
}

// GetAddedAt returns the value of AddedAt.
func (s *Peer) GetAddedAt() time.Time {
	return s.AddedAt
}

// SetName sets the value of Name.
func (s *Peer) SetName(val Name) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *Peer) SetURL(val DaemonURL) {
	s.URL = val
}

// SetStatus sets the value of Status.
func (s *Peer) SetStatus(val PeerStatus) {
	s.Status = val
}

// SetCode sets the value of Code.
func (s *Peer) SetCode(val Code) {
	s.Code = val
}

// SetAddedAt sets the value of AddedAt.
func (s *Peer) SetAddedAt(val time.Time) {
	s.AddedAt = val
}

// Who to ask to become peers.
// Ref: #/components/schemas/PeerInput
type PeerInput struct {
	Name Name      `json:"name"`
	URL  DaemonURL `json:"url"`
	Note OptNote   `json:"note"`
}

// GetName returns the value of Name.
func (s *PeerInput) GetName() Name {
	return s.Name
}

// GetURL returns the value of URL.
func (s *PeerInput) GetURL() DaemonURL {
	return s.URL
}

// GetNote returns the value of Note.
func (s *PeerInput) GetNote() OptNote {
	return s.Note
}

// SetName sets the value of Name.
func (s *PeerInput) SetName(val Name) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *PeerInput) SetURL(val DaemonURL) {
	s.URL = val
}

// SetNote sets the value of Note.
func (s *PeerInput) SetNote(val OptNote) {
	s.Note = val
}

// Peers, by name.
// Ref: #/components/schemas/PeerList
type PeerList struct {
	Peers []Peer `json:"peers"`
}

// GetPeers returns the value of Peers.
func (s *PeerList) GetPeers() []Peer {
	return s.Peers
}

// SetPeers sets the value of Peers.
func (s *PeerList) SetPeers(val []Peer) {
	s.Peers = val
}

type PeerSecret struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *PeerSecret) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *PeerSecret) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *PeerSecret) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *PeerSecret) SetRoles(val []string) {
	s.Roles = val
}

// `requested`: waiting for their owner to approve. `active`: both sides accept the secret.
type PeerStatus string

const (
	PeerStatusRequested PeerStatus = "requested"
	PeerStatusActive    PeerStatus = "active"
)

// AllValues returns all PeerStatus values.
func (PeerStatus) AllValues() []PeerStatus {
	return []PeerStatus{
		PeerStatusRequested,
		PeerStatusActive,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PeerStatus) MarshalText() ([]byte, error) {
	switch s {
	case PeerStatusRequested:
		return []byte(s), nil
	case PeerStatusActive:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PeerStatus) UnmarshalText(data []byte) error {
	switch PeerStatus(data) {
	case PeerStatusRequested:
		*s = PeerStatusRequested
		return nil
	case PeerStatusActive:
		*s = PeerStatusActive
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One daemon asking another to become peers.
// Ref: #/components/schemas/PeeringRequest
type PeeringRequest struct {
	Name Name      `json:"name"`
	URL  DaemonURL `json:"url"`
	// The secret both daemons will use, as `cpp_` and 43 base64url characters.
	Secret string  `json:"secret"`
	Note   OptNote `json:"note"`
}

// GetName returns the value of Name.
func (s *PeeringRequest) GetName() Name {
	return s.Name
}

// GetURL returns the value of URL.
func (s *PeeringRequest) GetURL() DaemonURL {
	return s.URL
}

// GetSecret returns the value of Secret.
func (s *PeeringRequest) GetSecret() string {
	return s.Secret
}

// GetNote returns the value of Note.
func (s *PeeringRequest) GetNote() OptNote {
	return s.Note
}

// SetName sets the value of Name.
func (s *PeeringRequest) SetName(val Name) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *PeeringRequest) SetURL(val DaemonURL) {
	s.URL = val
}

// SetSecret sets the value of Secret.
func (s *PeeringRequest) SetSecret(val string) {
	s.Secret = val
}

// SetNote sets the value of Note.
func (s *PeeringRequest) SetNote(val OptNote) {
	s.Note = val
}

// RFC 9457 problem details.
// Ref: #/components/schemas/Problem
type Problem struct {
	Type     OptString `json:"type"`
	Title    string    `json:"title"`
	Status   int32     `json:"status"`
	Detail   OptString `json:"detail"`
	Instance OptString `json:"instance"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *Problem) GetInstance() OptString {
	return s.Instance
}

// SetType sets the value of Type.
func (s *Problem) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *Problem) SetInstance(val OptString) {
	s.Instance = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// An event was stored, or already had been.
// Ref: #/components/schemas/Receipt
type Receipt struct {
	ID ID `json:"id"`
	// The event was already stored.
	Duplicate bool `json:"duplicate"`
}

// GetID returns the value of ID.
func (s *Receipt) GetID() ID {
	return s.ID
}

// GetDuplicate returns the value of Duplicate.
func (s *Receipt) GetDuplicate() bool {
	return s.Duplicate
}

// SetID sets the value of ID.
func (s *Receipt) SetID(val ID) {
	s.ID = val
}

// SetDuplicate sets the value of Duplicate.
func (s *Receipt) SetDuplicate(val bool) {
	s.Duplicate = val
}

// RemovePeerNoContent is response for RemovePeer operation.
type RemovePeerNoContent struct{}

// A peering request waiting for the owner.
// Ref: #/components/schemas/Request
type Request struct {
	ID   RequestRef `json:"id"`
	Name Name       `json:"name"`
	URL  DaemonURL  `json:"url"`
	Note OptNote    `json:"note"`
	Code Code       `json:"code"`
	At   time.Time  `json:"at"`
}

// GetID returns the value of ID.
func (s *Request) GetID() RequestRef {
	return s.ID
}

// GetName returns the value of Name.
func (s *Request) GetName() Name {
	return s.Name
}

// GetURL returns the value of URL.
func (s *Request) GetURL() DaemonURL {
	return s.URL
}

// GetNote returns the value of Note.
func (s *Request) GetNote() OptNote {
	return s.Note
}

// GetCode returns the value of Code.
func (s *Request) GetCode() Code {
	return s.Code
}

// GetAt returns the value of At.
func (s *Request) GetAt() time.Time {
	return s.At
}

// SetID sets the value of ID.
func (s *Request) SetID(val RequestRef) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Request) SetName(val Name) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *Request) SetURL(val DaemonURL) {
	s.URL = val
}

// SetNote sets the value of Note.
func (s *Request) SetNote(val OptNote) {
	s.Note = val
}

// SetCode sets the value of Code.
func (s *Request) SetCode(val Code) {
	s.Code = val
}

// SetAt sets the value of At.
func (s *Request) SetAt(val time.Time) {
	s.At = val
}

// Pending peering requests.
// Ref: #/components/schemas/RequestList
type RequestList struct {
	Requests []Request `json:"requests"`
}

// GetRequests returns the value of Requests.
func (s *RequestList) GetRequests() []Request {
	return s.Requests
}

// SetRequests sets the value of Requests.
func (s *RequestList) SetRequests(val []Request) {
	s.Requests = val
}

// A peering request was received and waits for the owner.
// Ref: #/components/schemas/RequestReceipt
type RequestReceipt struct {
	Status RequestReceiptStatus `json:"status"`
	Code   Code                 `json:"code"`
}

// GetStatus returns the value of Status.
func (s *RequestReceipt) GetStatus() RequestReceiptStatus {
	return s.Status
}

// GetCode returns the value of Code.
func (s *RequestReceipt) GetCode() Code {
	return s.Code
}

// SetStatus sets the value of Status.
func (s *RequestReceipt) SetStatus(val RequestReceiptStatus) {
	s.Status = val
}

// SetCode sets the value of Code.
func (s *RequestReceipt) SetCode(val Code) {
	s.Code = val
}

type RequestReceiptStatus string

const (
	RequestReceiptStatusPending RequestReceiptStatus = "pending"
)

// AllValues returns all RequestReceiptStatus values.
func (RequestReceiptStatus) AllValues() []RequestReceiptStatus {
	return []RequestReceiptStatus{
		RequestReceiptStatusPending,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RequestReceiptStatus) MarshalText() ([]byte, error) {
	switch s {
	case RequestReceiptStatusPending:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RequestReceiptStatus) UnmarshalText(data []byte) error {
	switch RequestReceiptStatus(data) {
	case RequestReceiptStatusPending:
		*s = RequestReceiptStatusPending
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RequestRef string

// Merged schema.
// Ref: #/components/schemas/Thread
type Thread struct {
	ID        ID         `json:"id"`
	Title     Title      `json:"title"`
	Kind      ThreadKind `json:"kind"`
	Labels    Labels     `json:"labels"`
	Sender    Name       `json:"sender"`
	Recipient Name       `json:"recipient"`
	Peer      Name       `json:"peer"`
	// The owner's part. `sender`: they opened it and close, reopen or withdraw it. `recipient`: they were
	// asked and ack, ask, resolve or decline it.
	Role  ThreadRole  `json:"role"`
	State ThreadState `json:"state"`
	Turn  OptName     `json:"turn"`
	// The thread is waiting on the owner.
	MyTurn bool `json:"myTurn"`
	// What the owner may do now, for actOnThread. `comment` is always among them.
	Actions     []Action  `json:"actions"`
	OpenedAt    time.Time `json:"openedAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Events      Count     `json:"events"`
	Undelivered Count     `json:"undelivered"`
	Failed      Count     `json:"failed"`
	// The thread's events in replay order.
	Log []ThreadEvent `json:"log"`
}

// GetID returns the value of ID.
func (s *Thread) GetID() ID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Thread) GetTitle() Title {
	return s.Title
}

// GetKind returns the value of Kind.
func (s *Thread) GetKind() ThreadKind {
	return s.Kind
}

// GetLabels returns the value of Labels.
func (s *Thread) GetLabels() Labels {
	return s.Labels
}

// GetSender returns the value of Sender.
func (s *Thread) GetSender() Name {
	return s.Sender
}

// GetRecipient returns the value of Recipient.
func (s *Thread) GetRecipient() Name {
	return s.Recipient
}

// GetPeer returns the value of Peer.
func (s *Thread) GetPeer() Name {
	return s.Peer
}

// GetRole returns the value of Role.
func (s *Thread) GetRole() ThreadRole {
	return s.Role
}

// GetState returns the value of State.
func (s *Thread) GetState() ThreadState {
	return s.State
}

// GetTurn returns the value of Turn.
func (s *Thread) GetTurn() OptName {
	return s.Turn
}

// GetMyTurn returns the value of MyTurn.
func (s *Thread) GetMyTurn() bool {
	return s.MyTurn
}

// GetActions returns the value of Actions.
func (s *Thread) GetActions() []Action {
	return s.Actions
}

// GetOpenedAt returns the value of OpenedAt.
func (s *Thread) GetOpenedAt() time.Time {
	return s.OpenedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Thread) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetEvents returns the value of Events.
func (s *Thread) GetEvents() Count {
	return s.Events
}

// GetUndelivered returns the value of Undelivered.
func (s *Thread) GetUndelivered() Count {
	return s.Undelivered
}

// GetFailed returns the value of Failed.
func (s *Thread) GetFailed() Count {
	return s.Failed
}

// GetLog returns the value of Log.
func (s *Thread) GetLog() []ThreadEvent {
	return s.Log
}

// SetID sets the value of ID.
func (s *Thread) SetID(val ID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Thread) SetTitle(val Title) {
	s.Title = val
}

// SetKind sets the value of Kind.
func (s *Thread) SetKind(val ThreadKind) {
	s.Kind = val
}

// SetLabels sets the value of Labels.
func (s *Thread) SetLabels(val Labels) {
	s.Labels = val
}

// SetSender sets the value of Sender.
func (s *Thread) SetSender(val Name) {
	s.Sender = val
}

// SetRecipient sets the value of Recipient.
func (s *Thread) SetRecipient(val Name) {
	s.Recipient = val
}

// SetPeer sets the value of Peer.
func (s *Thread) SetPeer(val Name) {
	s.Peer = val
}

// SetRole sets the value of Role.
func (s *Thread) SetRole(val ThreadRole) {
	s.Role = val
}

// SetState sets the value of State.
func (s *Thread) SetState(val ThreadState) {
	s.State = val
}

// SetTurn sets the value of Turn.
func (s *Thread) SetTurn(val OptName) {
	s.Turn = val
}

// SetMyTurn sets the value of MyTurn.
func (s *Thread) SetMyTurn(val bool) {
	s.MyTurn = val
}

// SetActions sets the value of Actions.
func (s *Thread) SetActions(val []Action) {
	s.Actions = val
}

// SetOpenedAt sets the value of OpenedAt.
func (s *Thread) SetOpenedAt(val time.Time) {
	s.OpenedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Thread) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetEvents sets the value of Events.
func (s *Thread) SetEvents(val Count) {
	s.Events = val
}

// SetUndelivered sets the value of Undelivered.
func (s *Thread) SetUndelivered(val Count) {
	s.Undelivered = val
}

// SetFailed sets the value of Failed.
func (s *Thread) SetFailed(val Count) {
	s.Failed = val
}

// SetLog sets the value of Log.
func (s *Thread) SetLog(val []ThreadEvent) {
	s.Log = val
}

// A reply or a move on a thread.
// Ref: #/components/schemas/ThreadAction
type ThreadAction struct {
	Action Action  `json:"action"`
	Body   OptBody `json:"body"`
}

// GetAction returns the value of Action.
func (s *ThreadAction) GetAction() Action {
	return s.Action
}

// GetBody returns the value of Body.
func (s *ThreadAction) GetBody() OptBody {
	return s.Body
}

// SetAction sets the value of Action.
func (s *ThreadAction) SetAction(val Action) {
	s.Action = val
}

// SetBody sets the value of Body.
func (s *ThreadAction) SetBody(val OptBody) {
	s.Body = val
}

// One event in a thread, as this daemon holds it.
// Ref: #/components/schemas/ThreadEvent
type ThreadEvent struct {
	ID     ID        `json:"id"`
	From   Name      `json:"from"`
	At     time.Time `json:"at"`
	Action Action    `json:"action"`
	Body   OptBody   `json:"body"`
	// Why the event did not change the thread: the other side's action came first, or it was not its
	// author's to take. Its body still stands.
	Ignored  OptString   `json:"ignored"`
	Delivery OptDelivery `json:"delivery"`
}

// GetID returns the value of ID.
func (s *ThreadEvent) GetID() ID {
	return s.ID
}

// GetFrom returns the value of From.
func (s *ThreadEvent) GetFrom() Name {
	return s.From
}

// GetAt returns the value of At.
func (s *ThreadEvent) GetAt() time.Time {
	return s.At
}

// GetAction returns the value of Action.
func (s *ThreadEvent) GetAction() Action {
	return s.Action
}

// GetBody returns the value of Body.
func (s *ThreadEvent) GetBody() OptBody {
	return s.Body
}

// GetIgnored returns the value of Ignored.
func (s *ThreadEvent) GetIgnored() OptString {
	return s.Ignored
}

// GetDelivery returns the value of Delivery.
func (s *ThreadEvent) GetDelivery() OptDelivery {
	return s.Delivery
}

// SetID sets the value of ID.
func (s *ThreadEvent) SetID(val ID) {
	s.ID = val
}

// SetFrom sets the value of From.
func (s *ThreadEvent) SetFrom(val Name) {
	s.From = val
}

// SetAt sets the value of At.
func (s *ThreadEvent) SetAt(val time.Time) {
	s.At = val
}

// SetAction sets the value of Action.
func (s *ThreadEvent) SetAction(val Action) {
	s.Action = val
}

// SetBody sets the value of Body.
func (s *ThreadEvent) SetBody(val OptBody) {
	s.Body = val
}

// SetIgnored sets the value of Ignored.
func (s *ThreadEvent) SetIgnored(val OptString) {
	s.Ignored = val
}

// SetDelivery sets the value of Delivery.
func (s *ThreadEvent) SetDelivery(val OptDelivery) {
	s.Delivery = val
}

// `request`: a resolution is expected. `fyi`: none is; acknowledging it closes it.
// Ref: #/components/schemas/ThreadKind
type ThreadKind string

const (
	ThreadKindRequest ThreadKind = "request"
	ThreadKindFyi     ThreadKind = "fyi"
)

// AllValues returns all ThreadKind values.
func (ThreadKind) AllValues() []ThreadKind {
	return []ThreadKind{
		ThreadKindRequest,
		ThreadKindFyi,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ThreadKind) MarshalText() ([]byte, error) {
	switch s {
	case ThreadKindRequest:
		return []byte(s), nil
	case ThreadKindFyi:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ThreadKind) UnmarshalText(data []byte) error {
	switch ThreadKind(data) {
	case ThreadKindRequest:
		*s = ThreadKindRequest
		return nil
	case ThreadKindFyi:
		*s = ThreadKindFyi
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Threads, newest activity first.
// Ref: #/components/schemas/ThreadList
type ThreadList struct {
	Threads []ThreadSummary `json:"threads"`
}

// GetThreads returns the value of Threads.
func (s *ThreadList) GetThreads() []ThreadSummary {
	return s.Threads
}

// SetThreads sets the value of Threads.
func (s *ThreadList) SetThreads(val []ThreadSummary) {
	s.Threads = val
}

// The owner's part. `sender`: they opened it and close, reopen or withdraw it. `recipient`: they were
// asked and ack, ask, resolve or decline it.
type ThreadRole string

const (
	ThreadRoleSender    ThreadRole = "sender"
	ThreadRoleRecipient ThreadRole = "recipient"
)

// AllValues returns all ThreadRole values.
func (ThreadRole) AllValues() []ThreadRole {
	return []ThreadRole{
		ThreadRoleSender,
		ThreadRoleRecipient,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ThreadRole) MarshalText() ([]byte, error) {
	switch s {
	case ThreadRoleSender:
		return []byte(s), nil
	case ThreadRoleRecipient:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ThreadRole) UnmarshalText(data []byte) error {
	switch ThreadRole(data) {
	case ThreadRoleSender:
		*s = ThreadRoleSender
		return nil
	case ThreadRoleRecipient:
		*s = ThreadRoleRecipient
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Where a thread is in its workflow. `closed`, `declined` and `withdrawn` end it; a closed thread can
// be reopened.
// Ref: #/components/schemas/ThreadState
type ThreadState string

const (
	ThreadStateOpen       ThreadState = "open"
	ThreadStateAcked      ThreadState = "acked"
	ThreadStateNeedsInput ThreadState = "needs-input"
	ThreadStateResolved   ThreadState = "resolved"
	ThreadStateClosed     ThreadState = "closed"
	ThreadStateDeclined   ThreadState = "declined"
	ThreadStateWithdrawn  ThreadState = "withdrawn"
)

// AllValues returns all ThreadState values.
func (ThreadState) AllValues() []ThreadState {
	return []ThreadState{
		ThreadStateOpen,
		ThreadStateAcked,
		ThreadStateNeedsInput,
		ThreadStateResolved,
		ThreadStateClosed,
		ThreadStateDeclined,
		ThreadStateWithdrawn,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ThreadState) MarshalText() ([]byte, error) {
	switch s {
	case ThreadStateOpen:
		return []byte(s), nil
	case ThreadStateAcked:
		return []byte(s), nil
	case ThreadStateNeedsInput:
		return []byte(s), nil
	case ThreadStateResolved:
		return []byte(s), nil
	case ThreadStateClosed:
		return []byte(s), nil
	case ThreadStateDeclined:
		return []byte(s), nil
	case ThreadStateWithdrawn:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ThreadState) UnmarshalText(data []byte) error {
	switch ThreadState(data) {
	case ThreadStateOpen:
		*s = ThreadStateOpen
		return nil
	case ThreadStateAcked:
		*s = ThreadStateAcked
		return nil
	case ThreadStateNeedsInput:
		*s = ThreadStateNeedsInput
		return nil
	case ThreadStateResolved:
		*s = ThreadStateResolved
		return nil
	case ThreadStateClosed:
		*s = ThreadStateClosed
		return nil
	case ThreadStateDeclined:
		*s = ThreadStateDeclined
		return nil
	case ThreadStateWithdrawn:
		*s = ThreadStateWithdrawn
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A thread without its events.
// Ref: #/components/schemas/ThreadSummary
type ThreadSummary struct {
	ID        ID         `json:"id"`
	Title     Title      `json:"title"`
	Kind      ThreadKind `json:"kind"`
	Labels    Labels     `json:"labels"`
	Sender    Name       `json:"sender"`
	Recipient Name       `json:"recipient"`
	Peer      Name       `json:"peer"`
	// The owner's part. `sender`: they opened it and close, reopen or withdraw it. `recipient`: they were
	// asked and ack, ask, resolve or decline it.
	Role  ThreadSummaryRole `json:"role"`
	State ThreadState       `json:"state"`
	Turn  OptName           `json:"turn"`
	// The thread is waiting on the owner.
	MyTurn bool `json:"myTurn"`
	// What the owner may do now, for actOnThread. `comment` is always among them.
	Actions     []Action  `json:"actions"`
	OpenedAt    time.Time `json:"openedAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Events      Count     `json:"events"`
	Undelivered Count     `json:"undelivered"`
	Failed      Count     `json:"failed"`
}

// GetID returns the value of ID.
func (s *ThreadSummary) GetID() ID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *ThreadSummary) GetTitle() Title {
	return s.Title
}

// GetKind returns the value of Kind.
func (s *ThreadSummary) GetKind() ThreadKind {
	return s.Kind
}

// GetLabels returns the value of Labels.
func (s *ThreadSummary) GetLabels() Labels {
	return s.Labels
}

// GetSender returns the value of Sender.
func (s *ThreadSummary) GetSender() Name {
	return s.Sender
}

// GetRecipient returns the value of Recipient.
func (s *ThreadSummary) GetRecipient() Name {
	return s.Recipient
}

// GetPeer returns the value of Peer.
func (s *ThreadSummary) GetPeer() Name {
	return s.Peer
}

// GetRole returns the value of Role.
func (s *ThreadSummary) GetRole() ThreadSummaryRole {
	return s.Role
}

// GetState returns the value of State.
func (s *ThreadSummary) GetState() ThreadState {
	return s.State
}

// GetTurn returns the value of Turn.
func (s *ThreadSummary) GetTurn() OptName {
	return s.Turn
}

// GetMyTurn returns the value of MyTurn.
func (s *ThreadSummary) GetMyTurn() bool {
	return s.MyTurn
}

// GetActions returns the value of Actions.
func (s *ThreadSummary) GetActions() []Action {
	return s.Actions
}

// GetOpenedAt returns the value of OpenedAt.
func (s *ThreadSummary) GetOpenedAt() time.Time {
	return s.OpenedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ThreadSummary) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetEvents returns the value of Events.
func (s *ThreadSummary) GetEvents() Count {
	return s.Events
}

// GetUndelivered returns the value of Undelivered.
func (s *ThreadSummary) GetUndelivered() Count {
	return s.Undelivered
}

// GetFailed returns the value of Failed.
func (s *ThreadSummary) GetFailed() Count {
	return s.Failed
}

// SetID sets the value of ID.
func (s *ThreadSummary) SetID(val ID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *ThreadSummary) SetTitle(val Title) {
	s.Title = val
}

// SetKind sets the value of Kind.
func (s *ThreadSummary) SetKind(val ThreadKind) {
	s.Kind = val
}

// SetLabels sets the value of Labels.
func (s *ThreadSummary) SetLabels(val Labels) {
	s.Labels = val
}

// SetSender sets the value of Sender.
func (s *ThreadSummary) SetSender(val Name) {
	s.Sender = val
}

// SetRecipient sets the value of Recipient.
func (s *ThreadSummary) SetRecipient(val Name) {
	s.Recipient = val
}

// SetPeer sets the value of Peer.
func (s *ThreadSummary) SetPeer(val Name) {
	s.Peer = val
}

// SetRole sets the value of Role.
func (s *ThreadSummary) SetRole(val ThreadSummaryRole) {
	s.Role = val
}

// SetState sets the value of State.
func (s *ThreadSummary) SetState(val ThreadState) {
	s.State = val
}

// SetTurn sets the value of Turn.
func (s *ThreadSummary) SetTurn(val OptName) {
	s.Turn = val
}

// SetMyTurn sets the value of MyTurn.
func (s *ThreadSummary) SetMyTurn(val bool) {
	s.MyTurn = val
}

// SetActions sets the value of Actions.
func (s *ThreadSummary) SetActions(val []Action) {
	s.Actions = val
}

// SetOpenedAt sets the value of OpenedAt.
func (s *ThreadSummary) SetOpenedAt(val time.Time) {
	s.OpenedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ThreadSummary) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetEvents sets the value of Events.
func (s *ThreadSummary) SetEvents(val Count) {
	s.Events = val
}

// SetUndelivered sets the value of Undelivered.
func (s *ThreadSummary) SetUndelivered(val Count) {
	s.Undelivered = val
}

// SetFailed sets the value of Failed.
func (s *ThreadSummary) SetFailed(val Count) {
	s.Failed = val
}

// The owner's part. `sender`: they opened it and close, reopen or withdraw it. `recipient`: they were
// asked and ack, ask, resolve or decline it.
type ThreadSummaryRole string

const (
	ThreadSummaryRoleSender    ThreadSummaryRole = "sender"
	ThreadSummaryRoleRecipient ThreadSummaryRole = "recipient"
)

// AllValues returns all ThreadSummaryRole values.
func (ThreadSummaryRole) AllValues() []ThreadSummaryRole {
	return []ThreadSummaryRole{
		ThreadSummaryRoleSender,
		ThreadSummaryRoleRecipient,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ThreadSummaryRole) MarshalText() ([]byte, error) {
	switch s {
	case ThreadSummaryRoleSender:
		return []byte(s), nil
	case ThreadSummaryRoleRecipient:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ThreadSummaryRole) UnmarshalText(data []byte) error {
	switch ThreadSummaryRole(data) {
	case ThreadSummaryRoleSender:
		*s = ThreadSummaryRoleSender
		return nil
	case ThreadSummaryRoleRecipient:
		*s = ThreadSummaryRoleRecipient
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Title string
